######################################################################
# Automatically generated by qmake (3.0) lun dic 23 15:01:03 2013
######################################################################

TEMPLATE = app
TARGET = Practica3
INCLUDEPATH += .

# Input
QT      += opengl
HEADERS += glwidget.h window.h
SOURCES += glwidget.cpp main.cpp window.cpp
